### ISSUE TITLE
Flask / oauth app failing to authorize the user during a rule action

### ISSUE THREAD

**Issue by Wopple** [Asana/python-asana#154]
I don't know what I'm doing wrong. I am creating a Flask application in python to build a custom rule action. I set up the oauth flow to authorize the app for my user. I can successfully install the app in my project, successfully build the rule action, but when I trigger the rule, the asana client fails to authorize as myself when getting resources. I'm using Flask-Cors for CORS and Flask-Session to persist the user's session to disk. I do see the session being persisted to disk with the access token and refresh token. Here's the relevant code snippets:

```python
import asana
from flask import Flask, session
from flask_cors import CORS
from flask_session import Session

# build the app
app = Flask(__name__)
app.config['SESSION_USE_SIGNER'] = True
app.config['SESSION_TYPE'] = 'filesystem'
CORS().init_app(app, origins='https://app.asana.com')
Session().init_app(app)

# custom client for added functionality
class AsanaClient(asana.Client):
    pass

def token_updater(token):
    session['token'] = token

# build the client within a request context
client = AsanaClient.oauth(
    auto_refresh_url='https://app.asana.com/-/oauth_token',
    client_id=current_app.client_id,
    client_secret=current_app.client_secret,
    redirect_uri=current_app.redirect_url,
    token=session.get('token'),
    token_updater=token_updater,
)

client.tasks.projects(task_id) # Unauthorized
```

I'm not seeing the session cookie in my browser, and I'm also seeing that my session doesn't have a token when creating the client even after a successful login / authorization. How am I supposed to figure out what credentials to use when receiving a request to run the action?

**Comment by Wopple** [comment]
So I dug into this more, and it appears the request being sent to my application does not have the session cookie in the request. The session cookie does appear in the oauth flow, but not the rule action trigger.

**Comment by jv-asana** [comment]
Hi @Wopple, due to security reasons we only send the `code` used to retrieve the users credentials once when the auth succeeds. When this happens you should fetch for the session token with the following: `<YOUR_CLIENT>.session.fetch_token(code=request.args.get('code'))` ([this part](https://github.com/Asana/python-asana/blob/master/examples/example-server.py#L69)) and store it. Based on your use case, we recommend that you store this information in a database instead of using Flask-Session/cookies.

The reason why we don't recommend using cookies for your use case is because you will encounter your current scenario. Because of the way rule action triggers work, your Flask-Sessions won't be able to retrieve the session token stored in your filesystem, redis, or browser. 

When your rule action is triggered you can retrieve the stored token from your database and pass it into the client to make the call. So something like: `<YOUR_CLIENT>(token=<YOUR_STORED_TOKEN>).users.me()` ([this part](https://github.com/Asana/python-asana/blob/master/examples/example-server.py#L32)).

Here's another example OAuth application ([summary_task.py](https://github.com/Asana/devrel-examples/blob/6ac7bcedd3843cfa7ac00bb7df28b886b61e3a6c/python/summary_task/summary_task.py)) you can reference. In this example we [store the credentials in an environment variable](https://github.com/Asana/devrel-examples/blob/6ac7bcedd3843cfa7ac00bb7df28b886b61e3a6c/python/summary_task/summary_task.py#L69-L70).

**Comment by Wopple** [comment]
Thanks. I guess I just needed to know that this behavior is intentional. I'll have to look up their oauth token by the user ID in the payload.
