### ISSUE TITLE
Python 3 compatibility with 0.6.0 release

### ISSUE THREAD

**Issue by smolesss** [Asana/python-asana#48]
Could not get pip3 to compile 0.6.0, but could get 0.5.1 to compile.

`$ sudo pip3 install asana
Collecting asana
  Downloading asana-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nbrt3fv9/asana/setup.py", line 8, in <module>
        from deploy import INIT_FILE, VERSION_REGEX
    ImportError: No module named 'deploy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nb                                                                                        rt3fv9/asana/
`

**Comment by praecipula** [comment]
Thanks for reporting this! I think it has something to do with a change that we made months ago to unify where versioning is controlled from; the "deploy" module is simply a file alongside our setup.py script that Travis CI runs when tests pass. This file pulls info from the Git tag to get the version for the egg, amongst other things. Clearly, this is not the environment that happens _inside_ of the deployed egg (no deploy script, no Travis, no Git), so that's going to fail. I'll get a chance to attempt a fix tomorrow!

**Comment by praecipula** [comment]
Hey, @smolesss, I put in a fix for this - with one intermediary release that, well, broke somewhere else and cost a patch version. Perhaps we'll implement CI tests that run unit tests _and test deploys_ in the future. In any case, this should be fixed with v0.6.2 now, let me know if that's not the case!

**Comment by Asana-Github** [comment]
➤ Matt Bramlage commented:<br />I fixed this and closed the GH issue<br />
