### ISSUE TITLE
error in install_requires

### ISSUE THREAD

**Issue by rilott** [Asana/python-asana#59]
Clean git checkout, execute python setup.py bdist_rpm

python --version: Python 2.7.5

> error in asana setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

I also receive this message when I try to pip install the package.

If I remove the parts after the first comma, the rpm builds:

```
diff --git a/setup.py b/setup.py
index 6adedd7..a1d2ce3 100755
--- a/setup.py
+++ b/setup.py
@@ -26,9 +26,9 @@ setup(
         'Programming Language :: Python :: 3.4'
     ],
     install_requires=[
-        'requests >=2.14.2, == 2.14.*',
-        'requests_oauthlib >= 0.6.1, == 0.6.*',
-        'six >= 1.10.0, == 1.10.*'
+        'requests >=2.14.2',
+        'requests_oauthlib >= 0.6.1',
+        'six >= 1.10.0'
     ],
     author='Asana, Inc',
     # author_email='',
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182692189208479/398848713596197)

**Comment by praecipula** [comment]
This is interesting because the current version specifier string was an attempt to keep our library compatible to older versions of `setuptools` that didn't yet follow the [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) version specifier of `~=`. If you follow that link, you'll see that the current strings are meant to be the "semantic meaning" that they suggest for an equivalent of `~=`, but it'd be a shame if that doesn't actually work.

This is tricky to test because we'd have to set up a machineVM image with its configuration to be just right to test it out. In any case, newer versions of `setuptools` [after version 8.0](http://setuptools.readthedocs.io/en/latest/history.html#id315) (Dec 2014) should have no problem with either way of specifying a compatible release.

Could you attach the output of what your machine says when you run

    pip show setuptools | grep Version

If it appears to be greater than 8.0, we'll have to dig in deeper.

Otherwise, you should be able to get moving by running

    pip install --upgrade setuptools

If that doesn't work, be sure to let us know!

**Comment by Asana-Github** [comment]
➤ Matt Bramlage commented:

I responded and upgraded this arbitrarily to tier P1 because we've heard variants of this from Dustin, and [R.J. Aquino](https://app.asana.com/0/15360926327075/15360926327075), and now this report. I still don't have any reason to believe that pip install --upgrade setuptools won't fix it, but it has been reported 3x, so maybe it's more widespread or otherwise broken...

**Comment by rilott** [comment]
```
[rilott python-asana]$ pip show setuptools | grep Version
Version: 2.0
```
Very interesting!

I also tried on a box that had setuptools 0.9.8 and I received the same message

**Comment by JshWright** [comment]
Do the dependencies need to be so tightly defined? It makes this a very difficult package to work with in any environment with more than a couple other packages.

For instance, requests_oathlib is ok with any version of requests >= 2.0. Does python-asana really need 2.14 exactly?

**Comment by theaeolianmachine** [comment]
Hey @JshWright, we're currently in the process of making this better and hope to cut a release soon with the efforts of #61 to make this less stringent.

**Comment by theaeolianmachine** [comment]
We recently cut a new release of v0.6.7 - feel free to try it out using a version of setuptools greater than 8.0, and let us know if you run into any issues!
