### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by daspecster** [Asana/python-asana#71]
Hello!

I was just curious if you had a project for your python 3 support and if you would want any help?

**Comment by theaeolianmachine** [comment]
Hi @daspecster,

Right now we're actively working on processes to revamp several of our client libraries, and as a result our Python and other libraries may change a good bit in the next several months (particularly because the code generation tools would be different). So for now, as much as we'd love the help, we'd hate to have to throw anything away.

That being said, once we start testing out the migration, Python 3 will be a clear goal of ours and we'll post back here with the work (if any) that will need to be done in order to support Python 3.

Thanks!

**Comment by datatalking** [comment]
@daspecster I'm creating one right now, something like a personal assistant to collect tasks with a due date or a few other items then push it to my asana instance. msg me for more.

@theaeolianmachine  let me know if I can publish the code to you or reference anything when I'm done later today.

**Comment by economy** [comment]
Is there an update for this? Trying to implement in 3.7, unable to get pagination to work in the Search API, but it looks like there's been no updates to documentation or development in awhile.

Happy to PR to update if that helps.

**Comment by beatboxchad** [comment]
We're coming up on Python2's EOL pretty quick here, I was actually a little surprised to discover this to be the source of my trouble using the library in a Python3 Django app.

Is this a priority for you guys? I'm slightly bummed I won't be able to create Asana tasks off a contact form as-is, but I understand that you have to focus on the core product.

Might you be willing to contract it out?

**Comment by daspecster** [comment]
I'm still willing to help if I can in some way!

**Comment by beatboxchad** [comment]
Wait -- did I read correctly you guys had planned to use some kind of metaprogramming/code generation tool, and that's why PR's here might be futile? Awesome!! If I was gonna do that, I'd use Clojure. Lisp is great for this kind of thing, and the JVM interop means we get native access to implementations of everybody's favorite garbage-collected languages. But I'm just spitballing here.

At any rate, what a great idea, and definitely the long-term move if you're trying to focus on your core product while keeping the developer experience ergonomic across many languages.

That said, I thank you in advance for indulging a soapbox of mine: This is a great example of how the Silicon Valley snake is eating its tail in recent years. It's now been nearly 18 months, the engineer who spoke on this doesn't appear to work at Asana, and the dialect this library is written in reaches End Of Life in less than 2 months. In engineering, laziness is a virtue. But sloth and greed remain deadly sins. :)

If you guys can confirm what your current long-term plans are with this, there's a vibrant community of Python developers and entrepreneurs ready and willing to collaborate. 2-to3 is a problem that's been on everybody's mind recently.

**Comment by beatboxchad** [comment]
(And maybe you could use the PR's to train your AI)

**Comment by beatboxchad** [comment]
Killed my previous comments because they were fun for me but not productive.

So it looks like you use gulp.js in some fancy way to build all the API's from metadata. It all works from https://github.com/Asana/asana-api-meta

I only JS when I have to, but at first glance it doesn't look like the Python templates are actually maintained by Asana? It's, what, a gulp plugin?

If so, it's just a matter of waiting for upstream? Who do we pester? I'm blocked. :)

**Comment by beatboxchad** [comment]
Finishing up my little hackathon here, all the generated code lives under `/gen/`, and I just ran a little `2to3` on my fork and it didn't touch anything under there. Presumably, PR's on anything outside that folder would be safe?

If you guys can confirm, there's at least two of us ready to fire away and get this thing updated.

I'm confident enough in my guess to give it a go. :)

**Comment by gangwere-aws** [comment]
Has any progress been made on this?

**Comment by rossgrambo** [comment]
Hello everyone! Since the last update, I've taken over the libraries and I am surprised to hear there's trouble with python3. 

We're currently debugging an issue with the "next" function in python 3 for collections, but I believe the rest of the library should work. 

I'd prefer to close this issue and create separate issues as they come, so I'll do that. But let me know if there's a major python 3 blocker I'm missing!
