### ISSUE TITLE
ASANA API update on new "gid" field

### ISSUE THREAD

**Issue by kittylon** [Asana/python-asana#83]
Hello, 

Since asana is migrating all float "id" to string "gid" fields for all resources, I am wondering if there are any plans to use the new field in this project?

Thanks!

**Comment by praecipula** [comment]
Hey @kittylon,

Since our client libraries are pretty thin wrappers around the JSON that gets returned from our API, new fields that get added are inherently backwards-compatible. You should start to see that the dictionary that is returned from our API with `id` fields will now also have a `gid` field as well.

If you want to see what the future behavior of our API will be after the change is fully made you can take a look at our [docs on this change](https://asana.com/developers/news/string-ids) to see how you can select the future behavior with a header. You can see how to do this in a [test in the client library](https://github.com/Asana/python-asana/blob/0637028d0733c93a9af7007bc89fb0cabc14d7af/tests/test_client.py#L33) by passing a `headers` keyword argument.

Did you have any other specific question about modifications you'd like to see in the client library due to this change?
